export const cursos = [
    {
        id: 0,
        categoria: "Frontend",
        logo: "https://png.pngtree.com/png-clipart/20200710/original/pngtree-books-logo-png-image_4135977.jpg",
        nome: "Criação de sites: Responsividade e Layouts para smartphone utilizando CSS com React",
        descricao: "Capacitar o estudante a transformar interfaces estáticas em aplicações web responsivas, utilizando as melhores práticas de CSS moderno integradas ao fluxo de desenvolvimento com React. O curso foca na mentalidade Mobile-First, ensinando como planejar e executar layouts que se adaptam perfeitamente de smartphones a desktops, garantindo uma experiência de navegação fluida em qualquer dispositivo.",
        duracao: "1 dia",
        cargaHoraria: "2 h",
        dataInicio: "20/04/2026",
        dataTermino: "20/04/2026",
        local: "Brasília",
        localEspc: "FINATEC - Fundação de Empreendimentos Científicos e Tecnológicos, Campus Universitário Darcy Ribeiro Av. L3 Norte, Ed - Asa Norte",
        requisitos: "Idade Mínima: 18 anos\nConhecimento Básico de ReactJS\nConhecimento Básico de CSS\nEquipamento: Trazer notebook pessoal (Windows ou Linux).",
        professor: "Luiz Henrique Morais Aguiar",
        fotoProfessor: "https://serverless-ocean-bucket-prod.s3.amazonaws.com/Speaker/1771169363760-C3CA943E-C444-40D7-8216-BACF892B3E56_4_5005_c.jpeg",
        graduacaoProfessor: "Graduado em Sistemas de Informação (2014) e mestre em Sistemas Mecatrônicos (2016). ",
        escolaProfessor: "Instituto Federal de Educação, Ciência e Tecnologia de Brasília (IFB) na área de Informática.",
        cursosProfesssor: "Criação de sites: Responsividade e Layouts para smartphone utilizando CSS com React",
        tipos: [
            {
                id: "presencial",
                texto: "Presencial",
            },
        ]
    },
    {
        id: 1,
        categoria: "Digital Health",
        logo: "https://png.pngtree.com/png-clipart/20200710/original/pngtree-books-logo-png-image_4135977.jpg",
        nome: "Aplicações de IoT na Área de Saúde",
        descricao: "O objetivo do curso é apresentar os conceitos fundamentais, as atuais tecnologias e exemplos reais de aplicações de IoT voltadas para a área de Saúde.",
        duracao: "1 dia",
        cargaHoraria: "2 h",
        dataInicio: "15/04/2026",
        dataTermino: "15/04/2026",
        local: "Online",
        localEspc: "Online",
        requisitos: "Idade Mínima: 18 anos",
        professor: "Claudia Patricia Ochoa Diaz",
        fotoProfessor: "https://serverless-ocean-bucket-prod.s3.amazonaws.com/Speaker/1771169178339-33727060-E233-4765-8CAC-7291435373D5_1_201_a.jpeg",  
        graduacaoProfessor: "Graduada em Engenharia Eletrônica, Mestre em Sistemas Mecatrônicos e Doutora em Sistemas Eletrônicos e de Automação. ",
        escolaProfessor: "Professora do Curso de Engenharia Eletrônica da FCTE/UnB. Vice-coordenadora da Plataforma Tecnológica BEM-TE-VI (PCTec/UnB).",
        cursosProfesssor: "Aplicações de IoT na Área de Saúde",
        tipos: [
            {
                id: "online",
                texto: "Online",
            },
        ]
    },
    {
        id: 2,
        categoria: "Fabricação Digital",
        logo: "https://png.pngtree.com/png-clipart/20200710/original/pngtree-books-logo-png-image_4135977.jpg",
        nome: "Processos de Fabricação e Introdução ao Software de modelagem 3D",
        descricao: "Introdução aos processos de manufatura digital, abordando os conceitos básicos de fabricação mecânica, o funcionamento das principais máquinas da indústria, baseadas na tecnologia CNC (Comando Numérico Computadorizado). Apresentar os fundamentos da modelagem 2D e 3D, bem como a utilização de softwares de desenho baseados em CAD/CAM.",
        duracao: "2 dia",
        cargaHoraria: "4 h",
        dataInicio: "15/04/2026",
        dataTermino: "22/04/2026",
        local: "Online",
        localEspc: "Online",
        requisitos: "Idade Mínima: 18 anos",
        professor: "Rafael Amoroso Marzolla",
        fotoProfessor: "https://serverless-ocean-bucket-prod.s3.amazonaws.com/Speaker/1775658315928-1571279633356.jpg",  
        graduacaoProfessor: " Graduado em Engenharia Mecânica pelo Insper. Tem experiência na indústria metalmecânica de máquinas ferramenta.",
        escolaProfessor: "Professor assistente dos cursos de engenharia mecânica e mecatrônica do Insper.",
        cursosProfesssor: "Processos de Fabricação e Introdução ao Software de modelagem 3D",
        tipos: [
            {
                id: "online",
                texto: "Online",
            },
        ]
    },
    {
        id: 3,
        categoria: "Backend",
        logo: "https://png.pngtree.com/png-clipart/20200710/original/pngtree-books-logo-png-image_4135977.jpg",
        nome: "Laboratório de Backend e Banco de Dados com MongoDB",
        descricao: "Com a aplicação desenvolvida no curso de Backend com NodeJs e Express, faremos a migração dos endpoints para funcionarem com o banco de dados MongoDB. Introduzindo o assunto sobre banco de dados, falando um pouco sobre SQL e NoSQL e os principais serviços que possibilitam essas tecnologias.",
        duracao: "1 dia",
        cargaHoraria: "4 h",
        dataInicio: "17/04/2026",
        dataTermino: "17/04/2026",
        local: "Manaus",
        localEspc: "Samsung OCEAN Manaus - Av. Darcy Vargas, 1200 - Parque Dez de Novembro, Manaus - AM, 69055-035",
        requisitos: "Idade Mínima: 18 anos",
        professor: "Moisés Pereira Bastos",
        fotoProfessor: "https://serverless-ocean-bucket-prod.s3.amazonaws.com/Speaker/1756836438349-C%C3%83%C2%B3pia-de-_V0A9638.jpg",  
        graduacaoProfessor: "Graduado em Engenharia da Computação pela UEA (2008) e mestrado em Engenharia Aeronáutica e Mecânica pelo Instituto Tecnológico de Aeronáutica (2010).",
        escolaProfessor: "Professor Pesquisador da Trilha de Blockchain e Backend em Samsung Ocean",
        cursosProfesssor: "Laboratório de Backend e Banco de Dados com MongoDB",
        tipos: [
            {
                id: "presencial",
                texto: "Presencial",
            },
        ]
    },
     {
        id: 4,
        categoria: "Desenvolvimento Ágil",
        logo: "https://png.pngtree.com/png-clipart/20200710/original/pngtree-books-logo-png-image_4135977.jpg",
        nome: "Desenvolvimento Ágil: Introdução",
        descricao: "Apresentar os conceitos básicos do ciclo de desenvolvimento de projetos, focando nos princípios, práticas e ferramentas associadas ao desenvolvimento ágil.",
        duracao: "1 dia",
        cargaHoraria: "3 h",
        dataInicio: "16/04/2026",
        dataTermino: "16/04/2026",
        local: "Manaus",
        localEspc: "Samsung OCEAN Manaus - Av. Darcy Vargas, 1200 - Parque Dez de Novembro, Manaus - AM, 69055-035",
        requisitos: "Idade Mínima: 18 anos",
        professor: "Larissa Pires da Silveira ",
        fotoProfessor: "https://serverless-ocean-bucket-prod.s3.amazonaws.com/Speaker/1755122551897-_V0A9755.jpg",  
        graduacaoProfessor: "Engenheira de Produção, Especialista em Gestão de Projetos e Mestranda em Propriedade Intelectual e Transferência de Tecnologia para Inovação/UEA.",
        escolaProfessor: "Professor Pesquisador da Trilha de Desenvolvimento Ágil em Samsung Ocean",
        cursosProfesssor: "Desenvolvimento Ágil: Introdução",
        tipos: [
            {
                id: "presencial",
                texto: "Presencial",
            },
        ]
    },
     {
        id: 5,
        categoria: "Metaverso",
        logo: "https://png.pngtree.com/png-clipart/20200710/original/pngtree-books-logo-png-image_4135977.jpg",
        nome: "Introdução ao Metaverso",
        descricao: "O Metaverso se apresenta como uma tecnologia disruptiva que já movimenta um mercado enorme e em plena expansão. As aplicações de Metaverso podem ser vistas em várias áreas e o domínio desse conceito pode fazer a diferença para quem quer estar sintonizado com as novidades mais recentes. Este curso oferece um conteúdo introdutório sobre Metaverso, permitindo que o aluno perceba a importância dessa tecnologia. De fato, o objetivo principal é que o aluno adquira uma visão mais pragmática, gradual e consistente sobre como ingressar nas tecnologias do Metaverso, seja como usuário – para perceber oportunidades de negócio, ou como profissional de TI – para desenvolver aplicações para este novo contexto.",
        duracao: "1 dia",
        cargaHoraria: "2 h",
        dataInicio: "17/04/2026",
        dataTermino: "17/04/2026",
        local: "Online",
        localEspc: "Online",
        requisitos: "Idade mínima: 18 anos\nCuriosidade por tecnologias disruptivas\nRecomendável: trazer laptop ou equipamento com algum poder de processamento para realização dos experimentos.",
        professor: "Fernando William Cruz",
        fotoProfessor: "https://serverless-ocean-bucket-prod.s3.amazonaws.com/Speaker/1771169870922-D35E1A08-30BD-43C9-9BA5-7DC2447BBF09_1_201_a.jpeg",  
        graduacaoProfessor: "Graduado em Processamento de Dados, mestre em Redes de Computadores e Sistemas Distribuídos; doutor em Ciência da Informação. ",
        escolaProfessor: "Professor Associado da FCTE/UnB Gama, atua no curso de Engenharia de Software.",
        cursosProfesssor: "Introdução ao Metaverso",
        tipos: [
            {
                id: "online",
                texto: "Online",
            },
        ]
    },
     {
        id: 6,
        categoria: "Metaverso",
        logo: "https://png.pngtree.com/png-clipart/20200710/original/pngtree-books-logo-png-image_4135977.jpg",
        nome: "Criação de Jogos 3D com Unity",
        descricao: "Desenvolver um jogo utilizando a ferramenta de desenvolvimento Unity. Coloque em prática seus conhecimentos, tire dúvidas e amplie seus horizontes no desenvolvimento de Jogos Digitais.",
        duracao: "2 d",
        cargaHoraria: "6 h",
        dataInicio: "22/04/2026",
        dataTermino: "23/04/2026",
        local: "Online",
        localEspc: "Online",
        requisitos: "Idade mínima: 18 anos",
        professor: "Gianluca Tessicini",
        fotoProfessor: "https://serverless-ocean-bucket-prod.s3.amazonaws.com/Speaker/1765230154638-WhatsApp-Image-2025-12-02-at-18.38.57.jpeg",  
        graduacaoProfessor: "Unity Developer e Tech Artist formado em Jogos Digitais. Desenvolve para PC, mobile e VR.",
        escolaProfessor: "Há 6 anos atua na Virtual Planet Technologies, criando experiências imersivas em Unity para entretenimento e comunicação científica.",
        cursosProfesssor: "Criação de Jogos 3D com Unity",
        tipos: [
            {
                id: "online",
                texto: "Online",
            },
        ]
    },
     {
        id: 7,
        categoria: "Inteligência Artificial",
        logo: "https://png.pngtree.com/png-clipart/20200710/original/pngtree-books-logo-png-image_4135977.jpg",
        nome: "Fundamentos de Agentes de IA: Conceitos e Implementações em Python",
        descricao: "Curso teórico e prático que objetiva apresentar os conceitos modernos de Agentes de IA com Grandes Modelos de Linguagem, suas aplicações e avanços. Ainda, visa demonstrar a construção de agentes de IA com ferramentas como Python, CrewAI e Langchain. Ao final do cursos, participantes terão visão do tema para concepção de soluções inovadoras.",
        duracao: "2 dias",
        cargaHoraria: "6 h",
        dataInicio: "23/04/2026",
        dataTermino: "24/04/2026",
        local: "Online",
        localEspc: "Online",
        requisitos: "Acima de 13 anos",
        professor: "Carlos Maurício Seródio Figueiredo",
        fotoProfessor: "https://serverless-ocean-bucket-prod.s3.amazonaws.com/Speaker/1753216088837-_V0A9521.jpg",  
        graduacaoProfessor: "Engenheiro Eletricista pela UFAM, mestre e doutor em Ciências da Computação pela UFMG. ",
        escolaProfessor: "Prof. Associado dos cursos de Computação da UEA. ",
        cursosProfesssor: "Fundamentos de Agentes de IA: Conceitos e Implementações em Python",
        tipos: [
            {
                id: "online",
                texto: "Online",
            },
        ]
    },
     {
        id: 8,
        categoria: "Inteligência Artificial",
        logo: "https://png.pngtree.com/png-clipart/20200710/original/pngtree-books-logo-png-image_4135977.jpg",
        nome: "IA Generativa na Prática com Ollama",
        descricao: "O curso busca introduzir os alunos ao universo das IAs generativas, com foco no uso prático do Ollama para execução de modelos localmente. Serão abordados os princípios fundamentais desses modelos, suas principais aplicações e como interagir com eles de forma eficiente no dia a dia. Por meio de uma abordagem teórico-prática, os participantes aprenderão a compreender as capacidades e limitações das IAs generativas, além de iniciar a experimentação com Python para integrar geração de conteúdo em seus próprios projetos. O curso também destaca o uso de modelos locais, promovendo maior controle, privacidade e independência de serviços externos.",
        duracao: "1 dia",
        cargaHoraria: "3 h",
        dataInicio: "23/04/2026",
        dataTermino: "23/04/2026",
        local: "Brasília",
        localEspc: "FINATEC - Fundação de Empreendimentos Científicos e Tecnológicos, Campus Universitário Darcy Ribeiro Av. L3 Norte, Ed - Asa Norte",
        requisitos: "Idade mínima: 18 anos\nConhecimento Básico de Machine Learning.",
        professor: "Eduardo Camargo de Siqueira",
        fotoProfessor: "https://serverless-ocean-bucket-prod.s3.amazonaws.com/Speaker/1768862093935-eduardo-siqueira.png",  
        graduacaoProfessor: "Graduado em Ciência da Computação, Mestre e doutor em Modelagem Matemática e Computacional. ",
        escolaProfessor: " Atua como pesquisador no Laboratório de IA (AILab) da UnB e no Laboratório de Aplicativos e Jogos do IFB.",
        cursosProfesssor: "IA Generativa na Prática com Ollama",
        tipos: [
            {
                id: "presencial",
                texto: "Presencial",
            },
        ]
    },
   
]