export const playlists = [
    {
        id: 0,
        logoCanal: "https://yt3.ggpht.com/ytc/AIdro_m-8zZRJBWMwnaHcJgQv2IRr0dLcqCv1yKcQHgSEZ26jHw=s48-c-k-c0x00ffffff-no-rj",
        canal: "Curso em Vídeo",
        fotoCapa:  "https://i.ibb.co/pBFjYZwx/download.jpg",
        nomePLaylist: "Curso Python ",
        videos: [
            {
                videoid: 0,
                titulo: "Curso Python #01 - Seja um Programador",
                link: "https://www.youtube.com/embed/S9uPNppGsGo?si=Y0wY3NVGQus__5AG",
                linkid: "S9uPNppGsGo",
                fotoCapa: "https://i.ibb.co/pBFjYZwx/download.jpg",
                descricao: "Você está pensando em ser um Programador e não sabe por onde começar? Pois nessa aula vamos te dar todas as informações e mostrar o caminho a seguir.",
            },
            {
                videoid: 1,
                titulo: "Curso Python #02 - Para que serve o Python?",
                link: "https://www.youtube.com/watch?v=Mp0vhMDI7fA",
                linkid: "Mp0vhMDI7fA",
                fotoCapa: "https://i.ibb.co/JjbRVY3N/download.jpg",
                descricao: "De onde vem o Python? Por que esse nome? Quais são as grandes empresas mundiais que usam Python em seus softwares? Essas e muitas outras perguntas serão respondidas nessa aula. ",
            },    
            {
                videoid: 2,
                titulo: "Curso Python #03 - Instalando o Python3 e o IDLE",
                link: "https://www.youtube.com/watch?v=VuKvR1J2LQE",
                linkid: "VuKvR1J2LQE",
                fotoCapa: "https://i.ibb.co/LzCKX5HW/hqdefault.jpg",
                descricao: "Entenda como funciona um Interpretador e veja como o Python funciona. Depois aprenda como instalar o Python 3.0 e o IDLE em seu computador com Windows, Linux ou Mac OS.",
            },
            {
                videoid: 3,
                titulo: "Curso Python #04 - Primeiros comandos em Python3",
                link: "https://www.youtube.com/watch?v=31llNGKWDdo",
                linkid: "31llNGKWDdo",
                fotoCapa: "https://i.ibb.co/hJ0zJLpd/download.jpg",
                descricao: "Agora chegou a hora de aprender os comandos básicos do Python e fazer os primeiros programas em Linguagem Python.",
            },
            {
                videoid: 4,
                titulo: "Curso Python #05 - Instalando o PyCharm e o QPython3",
                link: "https://www.youtube.com/watch?v=ElRd0cbXIv4",
                linkid: "ElRd0cbXIv4",
                fotoCapa: "https://i.ibb.co/VW2yRQWc/hq720.jpg",
                descricao: "Nesta aula, veremos como instalar e configurar a IDE (Integrated Development Environment) Python chamada PyCharm no Windows, MacOS e Linux. Além disso, veremos como programar Python no Android, utilizando o QPython3. ",
            },    
            {
                videoid: 5,
                titulo: "Curso Python #06 - Tipos Primitivos e Saída de Dados",
                link: "https://www.youtube.com/watch?v=hdDHg1p3YVc",
                linkid: "hdDHg1p3YVc",
                fotoCapa: "https://i.ibb.co/HDMmtywL/sddefault.jpg",
                descricao: "Nessa aula, vamos aprender como funcionam os tipos primitivos no Python e as peculiaridades do int() float() bool() e str(). Além disso, veremos como fazer as primeiras operações com a função print() do Python.",
            },      
        ] 
    },
    {
        id: 1,
        logoCanal: "https://yt3.ggpht.com/ytc/AIdro_m-8zZRJBWMwnaHcJgQv2IRr0dLcqCv1yKcQHgSEZ26jHw=s48-c-k-c0x00ffffff-no-rj",
        canal: "Curso em Vídeo",
        fotoCapa:  "https://i.ibb.co/ccsSgPY2/download.jpg",
        nomePLaylist: " Curso de Algoritmos",
        videos: [
            {
                videoid: 0,
                titulo: "Curso de Algoritmos #01 - Introdução a Algoritmos",
                link: "https://www.youtube.com/watch?v=8mei6uVttho",
                linkid: "8mei6uVttho",
                fotoCapa: "https://i.ibb.co/ccsSgPY2/download.jpg",
                descricao: "Aula do Curso de Algoritmo criado pelo professor Gustavo Guanabara para o portal CursoemVideo.com.",
            },
            {
                videoid: 1,
                titulo: "Curso de Algoritmos #02 - Primeiro Algoritmo",
                link: "https://www.youtube.com/watch?v=M2Af7gkbbro",
                linkid: "M2Af7gkbbro",
                fotoCapa: "https://i.ibb.co/jPzQtZGT/download.jpg",
                descricao: "Aula do Curso de Algoritmo criado pelo professor Gustavo Guanabara para o portal CursoemVideo.com.",
            },
               {
                videoid: 2,
                titulo: "Curso de Algoritmos #03 - Comando de Entrada e Operadores",
                link: "https://www.youtube.com/watch?v=RDrfZ-7WE8c",
                linkid: "RDrfZ-7WE8c",
                fotoCapa: "https://i.ibb.co/B2MBr6ms/download.jpg",
                descricao: "Aula do Curso de Algoritmo criado pelo professor Gustavo Guanabara para o portal CursoemVideo.com.",
            },
            {
                videoid: 3,
                titulo: "Curso de Algoritmos #04 - Operadores Lógicos e Relacionais",
                link: "https://www.youtube.com/watch?v=Ig4QZNpVZYs",
                linkid: "Ig4QZNpVZYs",
                fotoCapa: "https://i.ibb.co/pjns95PD/download.jpg",
                descricao: "Aula do Curso de Algoritmo criado pelo professor Gustavo Guanabara para o portal CursoemVideo.com.",
            },
        ] 
    },
    {
        id: 2,
        logoCanal: "https://yt3.ggpht.com/qpngKVOUPXoDYcwuMc2PoCWEpQHsWWWn7EwbkE5bD2Oha3xoD4mXFR4-4O4TWIt6wecr1_iFYQ=s88-c-k-c0x00ffffff-no-rj",
        canal: "Diogo Cortiz",
        fotoCapa:  "https://i.ibb.co/ntqzwsw/download.jpg",
        nomePLaylist: "Curso de Inteligência Artificial",
        videos: [
            {
                videoid: 0,
                titulo: "Aula 1 - Curso de Inteligência Artificial para todos ",
                link: "https://www.youtube.com/watch?v=Ze-Q6ZNWpco&t=3s",
                linkid: "Ze-Q6ZNWpco&t=3s",
                fotoCapa: "https://i.ibb.co/ntqzwsw/download.jpg",
                descricao: "Aula de Introdução à Inteligência Artificial.",
            },
            {
                videoid: 1,
                titulo: "Aula 2 - Regressão Linear",
                link: "https://www.youtube.com/watch?v=J9HuFIYcFWU",
                linkid: "J9HuFIYcFWU",
                fotoCapa: "https://i.ibb.co/bjftC00w/images.jpg",
                descricao: "Aula de Regressão Linear. ",
            },
              {
                videoid: 2,
                titulo: "Aula 3 - Árvore de Decisão",
                link: "https://www.youtube.com/watch?v=ecYpXd4WREk&t=3s",
                linkid: "ecYpXd4WREk&t=3s",
                fotoCapa: "https://i.ibb.co/nqmppN1m/download.jpg",
                descricao: "Esta é a 3a aula do Crash Course de Inteligência Artificial para todos.  Nesta aula, vamos aprender um pouco mais sobre aprendizado supervisionado em machine learning, trabalhando com uma técnica de classificação. Vamos trabalhar com um dataset real disponibilizado pelo Hospital Albert Einstein, com resultados de testes para covid-19. Também vamos aprender a avaliar um modelo usando Acurácia, F1-Score, Precisão, Recall e Matriz de Confusão.",
            },
            {
                videoid: 3,
                titulo: "Aula 4 - Derivadas descomplicadas para IA",
                link: "https://www.youtube.com/watch?v=WuPKvp_-X7Y&t=2s",
                linkid: "WuPKvp_-X7Y&t=2s",
                fotoCapa: "https://i.ibb.co/FLBR9W52/download.jpg",
                descricao: "Esta é a 4a aula do Crash Course de Inteligência Artificial para todos. Adaptei o curso de IA que dou para os alunos de mestrado e doutorado do TIDD/PUC-SP para que seja acessível para todos, independente da área de conhecimento. Nesta aula, vou apresentar os conceitos de derivadas de uma maneira intuitiva e focada para a área de Machine Learning. Vou mostrar como se calcula derivadas parciais, regra da potência e regra da cadeia. Esses são os fundamentos necessários para entendermos a próxima aula do curso, sobre Gradiente Descendente.",
            },
        ] 
    },
   
]